#File with constants used in the project

#BOARD
BOARD_MINIMUM_X = 5
BOARD_MINIMUM_Y = 5
BOARD_MAXIMUM_X = 24
BOARD_MAXIMUM_Y = 30

BOARD_DEFAULT_X = 10
BOARD_DEFAULT_Y = 8
BOARD_DEFAULT_MINECOUNT = 10

BOARD_MAX_ATTEMPT_COUNT = 10000

GAME_STATUS_ONGOING = "O"
GAME_STATUS_WIN = "W"
GAME_STATUS_LOSS = "L"

#TILE
STATUS_DEFAULT = "D"
STATUS_CLICKED = "C"
STATUS_FLAG = "F"

NAME_MINE = "M"

#Game
TIME_MAX = 9999

# (height, width, mineCount); E - easy, M - medium, H - hard,  X - expert, C - custom
GAME_MODES_DICT = {"E": (8,10, 10), "M":(16,16,40), "H":(16,30,100), "X":(24,30,200), "C":(-5,-5,-5)}
GAME_MODE_CUSTOM = "C"
GAME_MODES_NAMES = {"E": "Łatwy", "M": "Średni", "H": "Trudny", "X": "Ekspert", "C": "Własny"}

#Interface
INTERFACE_FILE_PATH = "data/style/"
INTERFACE_DEFAULT_AVAILABLE_STYLES = "stylDefault;stylDark"
INTERFACE_DEFAULT_AVAILABLE_STYLES_LIST = INTERFACE_DEFAULT_AVAILABLE_STYLES.split(";")
INTERFACE_DEFAULT_STYLE = "stylDefault"
INTERFACE_FILE_EXTENSION = ".gif"
INTERFACE_STYLE_NAME_FILE = "name.txt"

INTERFACE_GOODBYE_MESSAGE = "Czy napewno chcesz wyjść?"

INTERFACE_MENU_ITEMS_DICT = {"start":"menuStart.gif", "settings":"menuUstawienia.gif", "quit":"menuWyjscie.gif" }
INTERFACE_NAME_LABEL = ["name","menuName.gif"]
INTERFACE_BACKGROUND_COLOR_FILE = "backgroundcolor.txt"

#Settings Menu

SETTINGS_MENU_DEFAULT_STYLE = ";None;"
SETTINGS_MENU_DEFAULT_NUMBER = -1
SETTINGS_MENU_DEFAULT_WIDTH = 540
SETTINGS_MENU_DEFAULT_HEIGHT = 300
SETTINGS_MENU_BUTTON_BACKGROUND = "gray"
SETTINGS_MENU_BUTTON_FOREGROUND = "white"
SETTINGS_MENU_BUTTON_ACTIVE = "blue"

#Score Menu

SCORE_MENU_FILE_PATH = "data/wyniki.txt"
SCORE_MENU_KEY_NAME = "czasy"
SCORE_MENU_MAX_SCORE_SIZE = 10
SCORE_MENU_VALID_KEYS = list(GAME_MODES_DICT.keys())
SCORE_MENU_VALID_KEYS.remove(GAME_MODE_CUSTOM)
SCORE_MENU_DEFAULT_MODE = "E"
SCORE_MENU_DEFAULT_WIDTH = 400
SCORE_MENU_DEFAULT_HEIGHT = 300
SCORE_MENU_CURRENT_MODE_COLOR = "#72CD4B"
SCORE_MENU_DEFAULT_MODE_COLOR = "#73A0AE"
